version: '3'
services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server

  iot-service:
    build: ./iot-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server

  tracking-service:
    build: ./tracking-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server

  payment-service:
    build: ./payment-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server

  spring-admin:
    build: ./spring-admin
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8081:8080"
    command: start-dev


  iam-service:
    build: ./iam-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server


  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server

  audit-service:
    build: ./audit-service
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
