services:
  # Kafka (message broker)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ruta-kids-network

  # Kafka (message broker)
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ruta-kids-network

  # Config Server (allocated all configuration files for the microservices)
  config-server:
    build:
      context: .
      dockerfile: Dockerfile.config-server
      args:
        MODULE_NAME: config-server
    ports:
      - "8888:8888"
    container_name: config-server
    networks:
      - ruta-kids-network

  # Eureka Server (service registry)
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: eureka-server
    ports:
      - "8761:8761"
    container_name: eureka-server
    depends_on:
      - config-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - ruta-kids-network

  keycloak-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: keycloak-service
    container_name: keycloak-service
    depends_on:
      - config-server
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - ruta-kids-network

    # API Gateway (gateway service)
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: api-gateway
    container_name: api-gateway
    depends_on:
      - config-server
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - ruta-kids-network

networks:
  ruta-kids-network:
    driver: bridge