server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: iam-service
          uri: lb://iam-service
          predicates:
            - Path=/auth/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/rutakids/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

info:
  application:
    name: Api Gateway
    description: Pasarela central de servicios
    version: 1.0.0
  maintainer: "contacto@llantatech.org.pe"
  java-version: ${java.version}
  java-vendor: ${java.vendor}

management:
  endpoints:
    web:
      exposure:
        include: info
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  info:
    build:
      enabled: true
    git:
      enabled: true
    defaults:
      enabled: true
    env:
      enabled: true

logging:
  level:
    org.springframework.security: INFO
    org.springframework.cloud.gateway: DEBUG
