server:
  port: 8085

spring:
  application:
    name: iam-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/your-realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
