eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

name:
  value: rutakids-config

app:
  keycloak:
    client-id: ruta-kids-spring-service
    issuer-uri: ${KEYCLOAK_AUTH_SERVER_URL:https://auth.llantatech.org.pe/realms/rutakids_llanta}
    jwk-set-uri: ${app.keycloak.issuer-uri}/protocol/openid-connect/certs

spring:
  cloud:
    config:
      override-system-properties: false

#management:
#  tracing:
#    sampling:
#      probability: 1.0
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always
#  prometheus:
#    metrics:
#      export:
#        enabled: true
#  info:
#    build:
#      enabled: true
#    git:
#      enabled: true
#    defaults:
#      enabled: true
#    env:
#      enabled: true

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.springframework.security: INFO
    org.springframework.cloud.gateway: DEBUG