server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          route-id-prefix: ${spring.application.name}
      routes:
        - id: keycloak-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**
#        - id: iam-service
#          uri: lb://iam-service
#          predicates:
#            - Path=/auth/**

info:
  application:
    name: Api Gateway
    description: Pasarela central de servicios
    version: 1.0.0
  maintainer: "contacto@llantatech.org.pe"
  java-version: ${java.version}
  java-vendor: ${java.vendor}
