server:
  port: 8080

spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.issuer-uri}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          route-id-prefix: ${spring.application.name}
      routes:
        - id: keycloak-service
          uri: lb://keycloak-service
          predicates:
            - Path=/api/v1/auth/**

info:
  application:
    name: Api Gateway
    description: Pasarela central de servicios
    version: 1.0.0
  maintainer: "contacto@llantatech.org.pe"
  java-version: ${java.version}
  java-vendor: ${java.vendor}

logging:
  level:
    root: INFO
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.filter: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    org.pe.llantatech: DEBUG
