spring:
  application:
    name: keycloak-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_AUTH_SERVER_URL:https://auth.llantatech.org.pe/realms/rutakids_llanta}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: ruta-kids-spring-service
      principal-attributes : preferred_username

logging:
  level:
    org.pe.llantatech.keycloakservice: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /api/v1/auth/docs
  swagger-ui:
    enabled: false

#keycloak:
#  realm: ${KEYCLOAK_REALM:rutakids_llanta}
#  resource:
#  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:https://auth.llantatech.org.pe/realms/rutakids_llanta
#  ssl-required: external
#  use-resource-role-mappings: true

app:
  keycloak:
    login:
      url: https://auth.llantatech.org.pe/realms/rutakids_llanta/protocol/openid-connect/token
    grant-type: password
    client-id: ruta-kids-spring-service
    client-secret: ${KEYCLOAK_CLIENT_SECRET:eWn2jCfA4NA0vTv2ocEo5Me2YvioM2cx}