server:
  port: 8085

spring:
  application:
    name: iam-service
    username: sa
    password: password
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: mySecretKey1234567890
  expirationMs: 86400000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iamdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
